### ISSUE TITLE
Configuration du packaging en .jar

### ISSUE THREAD

**Issue by loicsteinmetz** [B4va/javabot#1]
Commandes : 

```
$ mvn package
$ java -jar target/javabot-1.0-SNAPSHOT.jar 
```

Erreur : 

```
Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/api/JDABuilder
	at org.asinfo.app.Main.main(Main.java:20)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.JDABuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

**Comment by loicsteinmetz** [comment]
```
Exception in thread "main" java.lang.NoClassDefFoundError: net/dv8tion/jda/api/JDABuilder
        at org.asinfo.app.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.JDABuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
```

Possible rapport avec variables de configs non récupérées ? voir #20

**Comment by loicsteinmetz** [comment]
Double packaging :

- Jar non exécutable sans les dépendances. Classpath intégré : `libs/` .
- Zip qui contient le jar **et** le dossier `libs/` et donc exécutable.

Problème (?) : pas possible de déployer un fichier *directement* exécutable.

> Basculer sur déploiement en war pour Tomcat, cf #2
